services:
  - type: web
    name: afia-orbit
    runtime: docker
    plan: free
    branch: backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: APP_NAME
        value: AFIA-ORBIT
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://afia-orbit.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        value: postgresql://afia_orbit_user:9pawdYvZdJiVcmR7iMZyUElcc1PFcfEr@dpg-d4b0qh24d50c73cv0m5g-a/afia_orbit
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_DOMAIN
        value: .afia-orbit.onrender.com
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: SESSION_HTTP_ONLY
        value: true
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@afia-orbit.com
      - key: MAIL_FROM_NAME
        value: AFIA-ORBIT
